version: '1'

services:
  nginx:
    image: nginx:1.25.1
    restart: always
    volumes:
      - ./nginx-selfsigned.crt:/etc/pki/tls/certs/nginx-selfsigned.crt
      - ./nginx-selfsigned.key:/etc/pki/tls/private/nginx-selfsigned.key
      - ./yourls.conf:/etc/nginx/conf.d/yourls.conf
    ports:
      - "443:443"
  yourls:
    image: yourls
    restart: always
    ports:
      - "80:80"
    env_file:
      - ./.env.yourls
    # Requires specific plugin folders, otherwise docker downloads other plugin folders from YOURLS repo
    volumes:
      - ./plugins/beanworks-api-request/:/var/www/html/user/plugins/beanworks-api-request/
      - ./plugins/domain-limiter/:/var/www/html/user/plugins/domain-limiter/
      - ./plugins/fallback-url/:/var/www/html/user/plugins/fallback-url/
      - ./plugins/google-auth/:/var/www/html/user/plugins/google-auth/
      - ./config.php:/var/www/html/user/config.php
      - ./index.php:/var/www/html/index.php
  mysql:
    image: mysql:8.0.22
    ports:
      - "3306:3306"
    expose:
      - "3306"
    restart: always
    env_file:
      - ./.env.mysql
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
