version: '1'

services:
  php:
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
        - "9000:9000"
    volumes:
      - ./:/var/www/html/
      - ./composer.json:/var/www/html/composer.json
      - ./composer.lock:/var/www/html/composer.lock
      - ./www.conf:/etc/php-fpm.d/www.conf
    environment:
      YOURLS_DB_NAME: yourlsdb
      YOURLS_DB_USER: admin
      YOURLS_DB_PASS: Bean2019
      YOURLS_DB_PREFIX: yourls_
  mysql:
    image: mysql:8.0.22
    ports:
        - "3306:3306"
    expose:
        - "3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Bean2019
      MYSQL_DATABASE: yourlsdb
      MYSQL_USER: admin
      MYSQL_PASSWORD: Bean2019
  nginx:
    image: nginx:latest
    restart: always
    volumes:
      - ./:/var/www/html/
      - ./nginx-selfsigned.crt:/etc/pki/tls/certs/nginx-selfsigned.crt
      - ./nginx-selfsigned.key:/etc/pki/tls/private/nginx-selfsigned.key
      - ./yourls.conf:/etc/nginx/conf.d/yourls.conf
    depends_on:
      - php
    ports:
      - "443:443"
      - "80:80"
    environment:
      YOURLS_DB_NAME: yourlsdb
      YOURLS_DB_USER: admin
      YOURLS_DB_PASS: Bean2019
      YOURLS_DB_PREFIX: yourls_
