apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: nginx
  name: nginx
spec:
  ports:
    - name: "443"
      port: 443
      targetPort: 443
  selector:
    io.kompose.service: nginx
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: nginx
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: nginx
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: nginx
    spec:
      containers:
        - image: nginx:1.25.1
          name: nginx
          ports:
            - containerPort: 443
          resources: {}
          volumeMounts:
          - name: nginx-selfsigned-crt
            mountPath: /etc/pki/tls/certs/nginx-selfsigned.crt
            subPath: nginx-selfsigned.crt
          - name: nginx-selfsigned-key
            mountPath: /etc/pki/tls/private/nginx-selfsigned.key
            subPath: nginx-selfsigned.key
          - name: nginx-yourls-conf
            mountPath: /etc/nginx/conf.d/yourls.conf
            subPath: yourls.conf
      restartPolicy: Always
      volumes:
        - name: nginx-selfsigned-crt
          configMap:
            name: nginx
            items:
              - key: nginx-selfsigned.crt
                path: nginx-selfsigned.crt
        - name: nginx-selfsigned-key
          configMap:
            name: nginx
            items:
              - key: nginx-selfsigned.key
                path: nginx-selfsigned.key
        - name: nginx-yourls-conf
          configMap:
            name: nginx
            items:
              - key: yourls.conf
                path: yourls.conf
status: {}
